version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: merchant-categories-api
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      # Connection string for SQL Server
      ConnectionStrings__DefaultConnection: "Server=db;Database=MerchantCategoriesApiDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;"

volumes:
  sqlserverdata:
